name: Naukri Auto Refresh (No Cookies)
on:
  schedule:
    - cron: '0 4 * * *' # Subah 9:30 AM IST
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Dependencies
        run: pip install selenium webdriver-manager
      - name: Run
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASS: ${{ secrets.NAUKRI_PASS }}
        run: python update_script.py
